/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ContractApprovalUpdateManyWithoutContractsInput } from "./ContractApprovalUpdateManyWithoutContractsInput";
import { ValidateNested, IsOptional, IsString, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { ContractPerformanceUpdateManyWithoutContractsInput } from "./ContractPerformanceUpdateManyWithoutContractsInput";
import { ContractQueryUpdateManyWithoutContractsInput } from "./ContractQueryUpdateManyWithoutContractsInput";
import { ContractReminderUpdateManyWithoutContractsInput } from "./ContractReminderUpdateManyWithoutContractsInput";
import { ContractVersionUpdateManyWithoutContractsInput } from "./ContractVersionUpdateManyWithoutContractsInput";
import { EnumContractStatus } from "./EnumContractStatus";

@InputType()
class ContractUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ContractApprovalUpdateManyWithoutContractsInput,
  })
  @ValidateNested()
  @Type(() => ContractApprovalUpdateManyWithoutContractsInput)
  @IsOptional()
  @Field(() => ContractApprovalUpdateManyWithoutContractsInput, {
    nullable: true,
  })
  contractApprovals?: ContractApprovalUpdateManyWithoutContractsInput;

  @ApiProperty({
    required: false,
    type: () => ContractPerformanceUpdateManyWithoutContractsInput,
  })
  @ValidateNested()
  @Type(() => ContractPerformanceUpdateManyWithoutContractsInput)
  @IsOptional()
  @Field(() => ContractPerformanceUpdateManyWithoutContractsInput, {
    nullable: true,
  })
  contractPerformances?: ContractPerformanceUpdateManyWithoutContractsInput;

  @ApiProperty({
    required: false,
    type: () => ContractQueryUpdateManyWithoutContractsInput,
  })
  @ValidateNested()
  @Type(() => ContractQueryUpdateManyWithoutContractsInput)
  @IsOptional()
  @Field(() => ContractQueryUpdateManyWithoutContractsInput, {
    nullable: true,
  })
  contractQueries?: ContractQueryUpdateManyWithoutContractsInput;

  @ApiProperty({
    required: false,
    type: () => ContractReminderUpdateManyWithoutContractsInput,
  })
  @ValidateNested()
  @Type(() => ContractReminderUpdateManyWithoutContractsInput)
  @IsOptional()
  @Field(() => ContractReminderUpdateManyWithoutContractsInput, {
    nullable: true,
  })
  contractReminders?: ContractReminderUpdateManyWithoutContractsInput;

  @ApiProperty({
    required: false,
    type: () => ContractVersionUpdateManyWithoutContractsInput,
  })
  @ValidateNested()
  @Type(() => ContractVersionUpdateManyWithoutContractsInput)
  @IsOptional()
  @Field(() => ContractVersionUpdateManyWithoutContractsInput, {
    nullable: true,
  })
  contractVersions?: ContractVersionUpdateManyWithoutContractsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumContractStatus,
  })
  @IsEnum(EnumContractStatus)
  @IsOptional()
  @Field(() => EnumContractStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  template?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  version?: string | null;
}

export { ContractUpdateInput as ContractUpdateInput };
