/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Contract as PrismaContract,
  ContractApproval as PrismaContractApproval,
  ContractPerformance as PrismaContractPerformance,
  ContractQuery as PrismaContractQuery,
  ContractReminder as PrismaContractReminder,
  ContractVersion as PrismaContractVersion,
} from "@prisma/client";

export class ContractServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ContractCountArgs, "select">): Promise<number> {
    return this.prisma.contract.count(args);
  }

  async contracts(
    args: Prisma.ContractFindManyArgs
  ): Promise<PrismaContract[]> {
    return this.prisma.contract.findMany(args);
  }
  async contract(
    args: Prisma.ContractFindUniqueArgs
  ): Promise<PrismaContract | null> {
    return this.prisma.contract.findUnique(args);
  }
  async createContract(
    args: Prisma.ContractCreateArgs
  ): Promise<PrismaContract> {
    return this.prisma.contract.create(args);
  }
  async updateContract(
    args: Prisma.ContractUpdateArgs
  ): Promise<PrismaContract> {
    return this.prisma.contract.update(args);
  }
  async deleteContract(
    args: Prisma.ContractDeleteArgs
  ): Promise<PrismaContract> {
    return this.prisma.contract.delete(args);
  }

  async findContractApprovals(
    parentId: string,
    args: Prisma.ContractApprovalFindManyArgs
  ): Promise<PrismaContractApproval[]> {
    return this.prisma.contract
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .contractApprovals(args);
  }

  async findContractPerformances(
    parentId: string,
    args: Prisma.ContractPerformanceFindManyArgs
  ): Promise<PrismaContractPerformance[]> {
    return this.prisma.contract
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .contractPerformances(args);
  }

  async findContractQueries(
    parentId: string,
    args: Prisma.ContractQueryFindManyArgs
  ): Promise<PrismaContractQuery[]> {
    return this.prisma.contract
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .contractQueries(args);
  }

  async findContractReminders(
    parentId: string,
    args: Prisma.ContractReminderFindManyArgs
  ): Promise<PrismaContractReminder[]> {
    return this.prisma.contract
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .contractReminders(args);
  }

  async findContractVersions(
    parentId: string,
    args: Prisma.ContractVersionFindManyArgs
  ): Promise<PrismaContractVersion[]> {
    return this.prisma.contract
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .contractVersions(args);
  }
}
