/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Query } from "./Query";
import { QueryCountArgs } from "./QueryCountArgs";
import { QueryFindManyArgs } from "./QueryFindManyArgs";
import { QueryFindUniqueArgs } from "./QueryFindUniqueArgs";
import { CreateQueryArgs } from "./CreateQueryArgs";
import { UpdateQueryArgs } from "./UpdateQueryArgs";
import { DeleteQueryArgs } from "./DeleteQueryArgs";
import { User } from "../../user/base/User";
import { QueryService } from "../query.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Query)
export class QueryResolverBase {
  constructor(
    protected readonly service: QueryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Query",
    action: "read",
    possession: "any",
  })
  async _queriesMeta(
    @graphql.Args() args: QueryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Query])
  @nestAccessControl.UseRoles({
    resource: "Query",
    action: "read",
    possession: "any",
  })
  async queries(@graphql.Args() args: QueryFindManyArgs): Promise<Query[]> {
    return this.service.queries(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Query, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Query",
    action: "read",
    possession: "own",
  })
  async query(
    @graphql.Args() args: QueryFindUniqueArgs
  ): Promise<Query | null> {
    const result = await this.service.query(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Query)
  @nestAccessControl.UseRoles({
    resource: "Query",
    action: "create",
    possession: "any",
  })
  async createQuery(@graphql.Args() args: CreateQueryArgs): Promise<Query> {
    return await this.service.createQuery({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Query)
  @nestAccessControl.UseRoles({
    resource: "Query",
    action: "update",
    possession: "any",
  })
  async updateQuery(
    @graphql.Args() args: UpdateQueryArgs
  ): Promise<Query | null> {
    try {
      return await this.service.updateQuery({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Query)
  @nestAccessControl.UseRoles({
    resource: "Query",
    action: "delete",
    possession: "any",
  })
  async deleteQuery(
    @graphql.Args() args: DeleteQueryArgs
  ): Promise<Query | null> {
    try {
      return await this.service.deleteQuery(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Query): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
