/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RankAdjustmentService } from "../rankAdjustment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RankAdjustmentCreateInput } from "./RankAdjustmentCreateInput";
import { RankAdjustment } from "./RankAdjustment";
import { RankAdjustmentFindManyArgs } from "./RankAdjustmentFindManyArgs";
import { RankAdjustmentWhereUniqueInput } from "./RankAdjustmentWhereUniqueInput";
import { RankAdjustmentUpdateInput } from "./RankAdjustmentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RankAdjustmentControllerBase {
  constructor(
    protected readonly service: RankAdjustmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RankAdjustment })
  @nestAccessControl.UseRoles({
    resource: "RankAdjustment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRankAdjustment(
    @common.Body() data: RankAdjustmentCreateInput
  ): Promise<RankAdjustment> {
    return await this.service.createRankAdjustment({
      data: {
        ...data,

        rank: data.rank
          ? {
              connect: data.rank,
            }
          : undefined,
      },
      select: {
        adjustmentReason: true,
        createdAt: true,
        effectiveDate: true,
        id: true,

        rank: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RankAdjustment] })
  @ApiNestedQuery(RankAdjustmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RankAdjustment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rankAdjustments(
    @common.Req() request: Request
  ): Promise<RankAdjustment[]> {
    const args = plainToClass(RankAdjustmentFindManyArgs, request.query);
    return this.service.rankAdjustments({
      ...args,
      select: {
        adjustmentReason: true,
        createdAt: true,
        effectiveDate: true,
        id: true,

        rank: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RankAdjustment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RankAdjustment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rankAdjustment(
    @common.Param() params: RankAdjustmentWhereUniqueInput
  ): Promise<RankAdjustment | null> {
    const result = await this.service.rankAdjustment({
      where: params,
      select: {
        adjustmentReason: true,
        createdAt: true,
        effectiveDate: true,
        id: true,

        rank: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RankAdjustment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RankAdjustment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRankAdjustment(
    @common.Param() params: RankAdjustmentWhereUniqueInput,
    @common.Body() data: RankAdjustmentUpdateInput
  ): Promise<RankAdjustment | null> {
    try {
      return await this.service.updateRankAdjustment({
        where: params,
        data: {
          ...data,

          rank: data.rank
            ? {
                connect: data.rank,
              }
            : undefined,
        },
        select: {
          adjustmentReason: true,
          createdAt: true,
          effectiveDate: true,
          id: true,

          rank: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RankAdjustment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RankAdjustment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRankAdjustment(
    @common.Param() params: RankAdjustmentWhereUniqueInput
  ): Promise<RankAdjustment | null> {
    try {
      return await this.service.deleteRankAdjustment({
        where: params,
        select: {
          adjustmentReason: true,
          createdAt: true,
          effectiveDate: true,
          id: true,

          rank: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
