/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PerformanceAppraisalService } from "../performanceAppraisal.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PerformanceAppraisalCreateInput } from "./PerformanceAppraisalCreateInput";
import { PerformanceAppraisal } from "./PerformanceAppraisal";
import { PerformanceAppraisalFindManyArgs } from "./PerformanceAppraisalFindManyArgs";
import { PerformanceAppraisalWhereUniqueInput } from "./PerformanceAppraisalWhereUniqueInput";
import { PerformanceAppraisalUpdateInput } from "./PerformanceAppraisalUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PerformanceAppraisalControllerBase {
  constructor(
    protected readonly service: PerformanceAppraisalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PerformanceAppraisal })
  @nestAccessControl.UseRoles({
    resource: "PerformanceAppraisal",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPerformanceAppraisal(
    @common.Body() data: PerformanceAppraisalCreateInput
  ): Promise<PerformanceAppraisal> {
    return await this.service.createPerformanceAppraisal({
      data: data,
      select: {
        applicant: true,
        createdAt: true,
        goalAchievement: true,
        id: true,
        reviewComment: true,
        selfEvaluation: true,
        status: true,
        supervisorComment: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PerformanceAppraisal] })
  @ApiNestedQuery(PerformanceAppraisalFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PerformanceAppraisal",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async performanceAppraisals(
    @common.Req() request: Request
  ): Promise<PerformanceAppraisal[]> {
    const args = plainToClass(PerformanceAppraisalFindManyArgs, request.query);
    return this.service.performanceAppraisals({
      ...args,
      select: {
        applicant: true,
        createdAt: true,
        goalAchievement: true,
        id: true,
        reviewComment: true,
        selfEvaluation: true,
        status: true,
        supervisorComment: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PerformanceAppraisal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PerformanceAppraisal",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async performanceAppraisal(
    @common.Param() params: PerformanceAppraisalWhereUniqueInput
  ): Promise<PerformanceAppraisal | null> {
    const result = await this.service.performanceAppraisal({
      where: params,
      select: {
        applicant: true,
        createdAt: true,
        goalAchievement: true,
        id: true,
        reviewComment: true,
        selfEvaluation: true,
        status: true,
        supervisorComment: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PerformanceAppraisal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PerformanceAppraisal",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePerformanceAppraisal(
    @common.Param() params: PerformanceAppraisalWhereUniqueInput,
    @common.Body() data: PerformanceAppraisalUpdateInput
  ): Promise<PerformanceAppraisal | null> {
    try {
      return await this.service.updatePerformanceAppraisal({
        where: params,
        data: data,
        select: {
          applicant: true,
          createdAt: true,
          goalAchievement: true,
          id: true,
          reviewComment: true,
          selfEvaluation: true,
          status: true,
          supervisorComment: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PerformanceAppraisal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PerformanceAppraisal",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePerformanceAppraisal(
    @common.Param() params: PerformanceAppraisalWhereUniqueInput
  ): Promise<PerformanceAppraisal | null> {
    try {
      return await this.service.deletePerformanceAppraisal({
        where: params,
        select: {
          applicant: true,
          createdAt: true,
          goalAchievement: true,
          id: true,
          reviewComment: true,
          selfEvaluation: true,
          status: true,
          supervisorComment: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
