/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PerformanceAppraisal } from "./PerformanceAppraisal";
import { PerformanceAppraisalCountArgs } from "./PerformanceAppraisalCountArgs";
import { PerformanceAppraisalFindManyArgs } from "./PerformanceAppraisalFindManyArgs";
import { Query } from "../../query/base/Query";
import { PerformanceAppraisalFindUniqueArgs } from "./PerformanceAppraisalFindUniqueArgs";
import { CreatePerformanceAppraisalArgs } from "./CreatePerformanceAppraisalArgs";
import { UpdatePerformanceAppraisalArgs } from "./UpdatePerformanceAppraisalArgs";
import { DeletePerformanceAppraisalArgs } from "./DeletePerformanceAppraisalArgs";
import { PerformanceAppraisalService } from "../performanceAppraisal.service";
@graphql.Resolver(() => PerformanceAppraisal)
export class PerformanceAppraisalResolverBase {
  constructor(protected readonly service: PerformanceAppraisalService) {}

  async _performanceAppraisalsMeta(
    @graphql.Args() args: PerformanceAppraisalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PerformanceAppraisal])
  async performanceAppraisals(
    @graphql.Args() args: PerformanceAppraisalFindManyArgs
  ): Promise<PerformanceAppraisal[]> {
    return this.service.performanceAppraisals(args);
  }

  @graphql.Query(() => PerformanceAppraisal, { nullable: true })
  async performanceAppraisal(
    @graphql.Args() args: PerformanceAppraisalFindUniqueArgs
  ): Promise<PerformanceAppraisal | null> {
    const result = await this.service.performanceAppraisal(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PerformanceAppraisal)
  async createPerformanceAppraisal(
    @graphql.Args() args: CreatePerformanceAppraisalArgs
  ): Promise<PerformanceAppraisal> {
    return await this.service.createPerformanceAppraisal({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => PerformanceAppraisal)
  async updatePerformanceAppraisal(
    @graphql.Args() args: UpdatePerformanceAppraisalArgs
  ): Promise<PerformanceAppraisal | null> {
    try {
      return await this.service.updatePerformanceAppraisal({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PerformanceAppraisal)
  async deletePerformanceAppraisal(
    @graphql.Args() args: DeletePerformanceAppraisalArgs
  ): Promise<PerformanceAppraisal | null> {
    try {
      return await this.service.deletePerformanceAppraisal(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
