/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Kpi } from "./Kpi";
import { KpiCountArgs } from "./KpiCountArgs";
import { KpiFindManyArgs } from "./KpiFindManyArgs";
import { Query } from "../../query/base/Query";
import { KpiFindUniqueArgs } from "./KpiFindUniqueArgs";
import { CreateKpiArgs } from "./CreateKpiArgs";
import { UpdateKpiArgs } from "./UpdateKpiArgs";
import { DeleteKpiArgs } from "./DeleteKpiArgs";
import { KpiService } from "../kpi.service";
@graphql.Resolver(() => Kpi)
export class KpiResolverBase {
  constructor(protected readonly service: KpiService) {}

  async _kpisMeta(
    @graphql.Args() args: KpiCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Kpi])
  async kpis(@graphql.Args() args: KpiFindManyArgs): Promise<Kpi[]> {
    return this.service.kpis(args);
  }

  @graphql.Query(() => Kpi, { nullable: true })
  async kpi(@graphql.Args() args: KpiFindUniqueArgs): Promise<Kpi | null> {
    const result = await this.service.kpi(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Kpi)
  async createKpi(@graphql.Args() args: CreateKpiArgs): Promise<Kpi> {
    return await this.service.createKpi({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Kpi)
  async updateKpi(@graphql.Args() args: UpdateKpiArgs): Promise<Kpi | null> {
    try {
      return await this.service.updateKpi({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Kpi)
  async deleteKpi(@graphql.Args() args: DeleteKpiArgs): Promise<Kpi | null> {
    try {
      return await this.service.deleteKpi(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
